Feature/mark sbcs as completed
peareasy/peareasy.github.io pull request #136
Opened 2022-10-11 15:49 UTC by christianhjelmslund

2022-10-12 07:20 UTC, christianhjelmslund commented on src/pages/SBCs/SBCPage.tsx
> +        promises.push(userSBCs(+id));
Vi kalder kun userSBCs hvis user er logged in

2022-10-13 13:05 UTC, sasp1 requested changes

2022-10-13 13:05 UTC, sasp1 commented on src/redux/sbcs/sbcSetsSlice.ts
> +    const resSolvedSBCSets = res[1] as userSBCSet[];
Det her er bare en FYI - hvis man i axios request sætter response typen behøver men ikke caste dem som det gøres her. 
Så `axios.get<userSBCSet>(url, headers)...`
Så behøver man ikke `as userSBCSet` i overstående 😊

2022-10-13 13:43 UTC, sasp1 approved these changes

2022-10-13 13:54 UTC, merged